import type { NewsSource } from "@/features/news-sources/news-source.types";

export const newsSourceRegistry: NewsSource[] = [
  {
    id: "rosstat",
    name: "Росстат",
    homepageUrl: "https://rosstat.gov.ru/",
    searchDomain: "rosstat.gov.ru",
    kind: "official-data",
    collectionMode: "web-search",
    priority: 1,
    topics: ["розничная торговля", "цены", "производство", "потребительский рынок"],
    note: "Первичный источник государственной статистики.",
    enabledForAgent: true,
  },
  {
    id: "cbr",
    name: "Банк России",
    homepageUrl: "https://cbr.ru/",
    searchDomain: "cbr.ru",
    kind: "official-data",
    collectionMode: "web-search",
    priority: 1,
    topics: ["инфляция", "платежи", "кредитование", "региональная экономика"],
    note: "Макроэкономика, платежное поведение и ценовые ожидания.",
    enabledForAgent: true,
  },
  {
    id: "fas",
    name: "ФАС России",
    homepageUrl: "https://fas.gov.ru/",
    searchDomain: "fas.gov.ru",
    kind: "regulator",
    collectionMode: "rss",
    feedUrl: "https://fas.gov.ru/news.rss",
    priority: 1,
    topics: ["ценообразование", "торговые сети", "конкуренция", "реклама"],
    note: "Регуляторные решения и проверки рынка.",
    enabledForAgent: true,
  },
  {
    id: "minpromtorg",
    name: "Минпромторг России",
    homepageUrl: "https://minpromtorg.gov.ru/",
    searchDomain: "minpromtorg.gov.ru",
    kind: "regulator",
    collectionMode: "web-search",
    priority: 1,
    topics: ["торговля", "маркировка", "промышленность", "регулирование"],
    note: "Официальные решения по внутренней торговле и промышленности.",
    enabledForAgent: true,
  },
  {
    id: "minselhoz",
    name: "Минсельхоз России",
    homepageUrl: "https://mcx.gov.ru/",
    searchDomain: "mcx.gov.ru",
    kind: "regulator",
    collectionMode: "web-search",
    priority: 1,
    topics: ["АПК", "сырье", "экспорт", "производство продуктов"],
    note: "Первичный источник по агропромышленному комплексу.",
    enabledForAgent: true,
  },
  {
    id: "rospotrebnadzor",
    name: "Роспотребнадзор",
    homepageUrl: "https://rospotrebnadzor.ru/",
    searchDomain: "rospotrebnadzor.ru",
    kind: "regulator",
    collectionMode: "web-search",
    priority: 1,
    topics: ["качество", "безопасность", "проверки", "права потребителей"],
    note: "Обязательные требования и безопасность товаров.",
    enabledForAgent: true,
  },
  {
    id: "rosselhoznadzor",
    name: "Россельхознадзор",
    homepageUrl: "https://fsvps.gov.ru/",
    searchDomain: "fsvps.gov.ru",
    kind: "regulator",
    collectionMode: "rss",
    feedUrl: "https://fsvps.gov.ru/news/rss",
    priority: 1,
    topics: ["ветеринарный контроль", "импорт", "экспорт", "Меркурий"],
    note: "Ограничения поставок и ветеринарный контроль.",
    enabledForAgent: true,
  },
  {
    id: "government",
    name: "Правительство России",
    homepageUrl: "https://government.ru/",
    searchDomain: "government.ru",
    kind: "regulator",
    collectionMode: "web-search",
    priority: 1,
    topics: ["торговля", "АПК", "налоги", "господдержка"],
    note: "Решения правительства и профильных комиссий.",
    enabledForAgent: true,
  },
  {
    id: "eec",
    name: "Евразийская экономическая комиссия",
    homepageUrl: "https://eec.eaeunion.org/",
    searchDomain: "eec.eaeunion.org",
    kind: "regulator",
    collectionMode: "web-search",
    priority: 2,
    topics: ["техрегламенты", "ЕАЭС", "маркировка", "внешняя торговля"],
    note: "Требования общего рынка ЕАЭС.",
    enabledForAgent: true,
  },
  {
    id: "acort",
    name: "АКОРТ",
    homepageUrl: "https://www.acort.ru/",
    searchDomain: "acort.ru",
    kind: "association",
    collectionMode: "web-search",
    priority: 1,
    topics: ["федеральные сети", "поставщики", "регулирование", "цены"],
    note: "Позиция крупнейших торговых сетей.",
    enabledForAgent: true,
  },
  {
    id: "akit",
    name: "АКИТ",
    homepageUrl: "https://www.akit.ru/",
    searchDomain: "akit.ru",
    kind: "association",
    collectionMode: "web-search",
    priority: 1,
    topics: ["e-commerce", "маркетплейсы", "объем рынка", "регулирование"],
    note: "Статистика и практика интернет-торговли.",
    enabledForAgent: true,
  },
  {
    id: "russretail",
    name: "Союз независимых сетей России",
    homepageUrl: "https://russretail.ru/",
    searchDomain: "russretail.ru",
    kind: "association",
    collectionMode: "web-search",
    priority: 2,
    topics: ["региональные сети", "закупки", "поставщики", "мероприятия"],
    note: "Региональный ритейл и независимые сети.",
    enabledForAgent: true,
  },
  {
    id: "data-insight",
    name: "Data Insight",
    homepageUrl: "https://datainsight.ru/",
    searchDomain: "datainsight.ru",
    kind: "research",
    collectionMode: "rss",
    feedUrl: "https://datainsight.ru/rss.xml",
    priority: 1,
    topics: ["e-commerce", "e-grocery", "логистика", "покупатель"],
    note: "Профильные исследования российского e-commerce.",
    enabledForAgent: true,
  },
  {
    id: "romir",
    name: "РОМИР",
    homepageUrl: "https://romir.ru/",
    searchDomain: "romir.ru",
    kind: "research",
    collectionMode: "web-search",
    priority: 2,
    topics: ["потребитель", "чек", "бренды", "спрос"],
    note: "Панельные исследования и потребительское поведение.",
    enabledForAgent: true,
  },
  {
    id: "infoline",
    name: "INFOLine",
    homepageUrl: "https://www.infoline.spb.ru/",
    searchDomain: "infoline.spb.ru",
    kind: "research",
    collectionMode: "web-search",
    priority: 2,
    topics: ["FMCG", "торговые сети", "e-grocery", "отраслевые рейтинги"],
    note: "Часть исследований платная; агент использует только открытые данные.",
    enabledForAgent: true,
  },
  {
    id: "retail-ru",
    name: "Retail.ru",
    homepageUrl: "https://www.retail.ru/",
    searchDomain: "retail.ru",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://www.retail.ru/rss/news",
    priority: 1,
    topics: ["ритейл", "поставщики", "СТМ", "логистика", "технологии"],
    note: "Профильное B2B-медиа для ритейлеров и поставщиков.",
    enabledForAgent: true,
  },
  {
    id: "new-retail",
    name: "New Retail",
    homepageUrl: "https://new-retail.ru/",
    searchDomain: "new-retail.ru",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://new-retail.ru/rss/index_all.php",
    priority: 1,
    topics: ["ритейл", "e-commerce", "FMCG", "маркетинг", "технологии"],
    note: "B2B-портал и открытая RSS-лента; Telegram используется как ручной радар.",
    enabledForAgent: true,
  },
  {
    id: "shoppers",
    name: "Shopper’s",
    homepageUrl: "https://shoppers.media/",
    searchDomain: "shoppers.media",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 1,
    topics: ["ритейл", "производители", "АПК", "технологии"],
    note: "Деловые новости розницы и потребительского рынка.",
    enabledForAgent: true,
  },
  {
    id: "market-media",
    name: "MarketMedia",
    homepageUrl: "https://marketmedia.ru/",
    searchDomain: "marketmedia.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["ритейл", "общепит", "торговая недвижимость", "технологии"],
    note: "Новости и аналитика потребительского рынка.",
    enabledForAgent: true,
  },
  {
    id: "milknews",
    name: "Milknews",
    homepageUrl: "https://milknews.ru/",
    searchDomain: "milknews.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 1,
    topics: ["молоко", "переработка", "сырье", "цены"],
    note: "Специализированное медиа молочного рынка.",
    enabledForAgent: true,
  },
  {
    id: "dairynews",
    name: "DairyNews",
    homepageUrl: "https://dairynews.today/",
    searchDomain: "dairynews.today",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://dairynews.today/rss",
    priority: 2,
    topics: ["молоко", "животноводство", "переработка", "экспорт"],
    note: "Новости молочной отрасли и производителей.",
    enabledForAgent: true,
  },
  {
    id: "sfera",
    name: "Sfera.fm",
    homepageUrl: "https://sfera.fm/",
    searchDomain: "sfera.fm",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://sfera.fm/rss",
    priority: 1,
    topics: ["пищевое производство", "молоко", "мясо", "рыба", "ингредиенты"],
    note: "Отраслевые данные по производству продуктов и ингредиентов.",
    enabledForAgent: true,
  },
  {
    id: "agroinvestor",
    name: "Агроинвестор",
    homepageUrl: "https://www.agroinvestor.ru/",
    searchDomain: "agroinvestor.ru",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://www.agroinvestor.ru/feed/public-agroinvestor-articles.xml",
    priority: 1,
    topics: ["АПК", "инвестиции", "производство", "экономика"],
    note: "Инвестиции и экономика агропромышленного комплекса.",
    enabledForAgent: true,
  },
  {
    id: "fruitnews",
    name: "FruitNews",
    homepageUrl: "https://fruitnews.ru/",
    searchDomain: "fruitnews.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["овощи", "фрукты", "импорт", "цены", "логистика"],
    note: "Свежая продукция, импорт и плодоовощной рынок.",
    enabledForAgent: true,
  },
  {
    id: "meatinfo",
    name: "Meatinfo",
    homepageUrl: "https://meatinfo.ru/",
    searchDomain: "meatinfo.ru",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://meatinfo.ru/news/rss",
    priority: 2,
    topics: ["мясо", "птица", "цены", "производство"],
    note: "Отраслевой мониторинг мясного рынка.",
    enabledForAgent: true,
  },
  {
    id: "agroxxi",
    name: "AgroXXI",
    homepageUrl: "https://www.agroxxi.ru/",
    searchDomain: "agroxxi.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 3,
    topics: ["растениеводство", "АПК", "агротехнологии"],
    note: "Дополнительный источник по сельхозсырью; требует перекрестной проверки.",
    enabledForAgent: true,
  },
  {
    id: "unipack",
    name: "Unipack.ru",
    homepageUrl: "https://news.unipack.ru/",
    searchDomain: "unipack.ru",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://news.unipack.ru/rss/",
    priority: 2,
    topics: ["упаковка", "маркировка", "оборудование", "сырье"],
    note: "Упаковочная индустрия и производственные технологии.",
    enabledForAgent: true,
  },
  {
    id: "fishnews",
    name: "Fishnews",
    homepageUrl: "https://fishnews.ru/",
    searchDomain: "fishnews.ru",
    kind: "industry-media",
    collectionMode: "rss",
    feedUrl: "https://fishnews.ru/rss",
    priority: 2,
    topics: ["рыба", "аквакультура", "переработка", "экспорт"],
    note: "Рыбная отрасль и регулирование поставок.",
    enabledForAgent: true,
  },
  {
    id: "logirus",
    name: "Логирус",
    homepageUrl: "https://logirus.ru/",
    searchDomain: "logirus.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 1,
    topics: ["логистика", "склады", "транспорт", "цепочки поставок"],
    note: "Профильные новости логистики; Telegram — дополнительный ручной радар.",
    enabledForAgent: true,
  },
  {
    id: "logistics-ru",
    name: "Логистика.ру",
    homepageUrl: "https://logistics.ru/",
    searchDomain: "logistics.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["ритейл", "склады", "доставка", "транспорт"],
    note: "Практика управления цепочками поставок.",
    enabledForAgent: true,
  },
  {
    id: "oborot",
    name: "Oborot.ru",
    homepageUrl: "https://oborot.ru/",
    searchDomain: "oborot.ru",
    kind: "industry-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["e-commerce", "маркетплейсы", "селлеры", "доставка"],
    note: "Практика интернет-торговли и продавцов.",
    enabledForAgent: true,
  },
  {
    id: "rbc",
    name: "РБК",
    homepageUrl: "https://www.rbc.ru/",
    searchDomain: "rbc.ru",
    kind: "business-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["компании", "финансы", "ритейл", "регулирование"],
    note: "Деловая повестка; ключевые факты проверяются по первоисточнику.",
    enabledForAgent: true,
  },
  {
    id: "kommersant",
    name: "Коммерсантъ",
    homepageUrl: "https://www.kommersant.ru/",
    searchDomain: "kommersant.ru",
    kind: "business-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["ритейл", "FMCG", "сделки", "регулирование"],
    note: "Деловые новости; платные страницы используются только как сигнал.",
    enabledForAgent: true,
  },
  {
    id: "tass",
    name: "ТАСС",
    homepageUrl: "https://tass.ru/",
    searchDomain: "tass.ru",
    kind: "business-media",
    collectionMode: "web-search",
    priority: 2,
    topics: ["экономика", "регулирование", "компании", "АПК"],
    note: "Оперативные сообщения и официальные заявления.",
    enabledForAgent: true,
  },
  {
    id: "x5",
    name: "X5",
    homepageUrl: "https://x5.ru/ru/press-center/",
    searchDomain: "x5.ru",
    kind: "company",
    collectionMode: "web-search",
    priority: 1,
    topics: ["Пятёрочка", "Перекрёсток", "Чижик", "поставщики", "логистика"],
    note: "Первичный корпоративный источник X5.",
    enabledForAgent: true,
  },
  {
    id: "magnit",
    name: "Магнит",
    homepageUrl: "https://www.magnit.com/ru/",
    searchDomain: "magnit.com",
    kind: "company",
    collectionMode: "web-search",
    priority: 1,
    topics: ["продуктовый ритейл", "дрогери", "поставщики", "результаты"],
    note: "Первичный корпоративный источник «Магнита».",
    enabledForAgent: true,
  },
  {
    id: "lenta",
    name: "Группа Лента",
    homepageUrl: "https://www.lentagroup.ru/ru/media/news-and-press-releases/",
    searchDomain: "lentagroup.ru",
    kind: "company",
    collectionMode: "web-search",
    priority: 1,
    topics: ["гипермаркеты", "супермаркеты", "поставщики", "результаты"],
    note: "Первичный корпоративный источник «Ленты».",
    enabledForAgent: true,
  },
  {
    id: "rwb",
    name: "RWB / Wildberries",
    homepageUrl: "https://rwb.ru/",
    searchDomain: "rwb.ru",
    kind: "company",
    collectionMode: "web-search",
    priority: 1,
    topics: ["маркетплейсы", "селлеры", "логистика", "реклама"],
    note: "Первичный источник объединённой компании Wildberries & Russ.",
    enabledForAgent: true,
  },
  {
    id: "fix-price",
    name: "Fix Price",
    homepageUrl: "https://media.fix-price.com/",
    searchDomain: "media.fix-price.com",
    kind: "company",
    collectionMode: "web-search",
    priority: 2,
    topics: ["non-food", "FMCG", "дискаунтеры", "результаты"],
    note: "Корпоративный пресс-центр Fix Price.",
    enabledForAgent: true,
  },
  {
    id: "mvideo",
    name: "М.Видео–Эльдорадо",
    homepageUrl: "https://www.mvideoeldorado.ru/ru/press-centr/",
    searchDomain: "mvideoeldorado.ru",
    kind: "company",
    collectionMode: "web-search",
    priority: 2,
    topics: ["non-food", "электроника", "маркетплейс", "FMCG"],
    note: "Корпоративные новости non-food и собственного маркетплейса.",
    enabledForAgent: true,
  },
  {
    id: "new-retail-telegram",
    name: "Telegram New Retail",
    homepageUrl: "https://t.me/NewRetail",
    searchDomain: "t.me",
    kind: "social",
    collectionMode: "manual",
    priority: 3,
    topics: ["оперативные сигналы", "ритейл", "e-commerce"],
    note: "Только ручной мониторинг; публикация проверяется по исходной статье.",
    enabledForAgent: false,
  },
  {
    id: "logirus-telegram",
    name: "Telegram Логирус",
    homepageUrl: "https://t.me/logirus",
    searchDomain: "t.me",
    kind: "social",
    collectionMode: "manual",
    priority: 3,
    topics: ["оперативные сигналы", "логистика"],
    note: "Только ручной мониторинг; не считается первоисточником.",
    enabledForAgent: false,
  },
];

export function getAgentSources(): NewsSource[] {
  return newsSourceRegistry.filter((source) => source.enabledForAgent);
}
